Wait what?

IÕve been working with Python and PySide for quite a while, but only just a
couple of months ago as my full-time job. As it has happened to me before, I
start to think Òwell, I really know this thing from head to toesÓ, and then I
realize I donÕt.

As a part of the LEAP Client a friend of mine started developing a log viewer
for the app. Since we were already using logging, what made most sense was to
have a logging.Handler subclass that harvested all the logs and then later on
display those in a nice dialog. While the dialog is open, it needs to receive
new logs, and for that of course we used the mighty signals.

HereÕs where it got tricky. Being good devs, we are using PySideÕs new style
signal handling, but when the time came to actually emit it, hereÕs the error
message we got:

  
<table>  
<tr>  
<td>

Objecto

</td>  
<td>

A

</td>  
<td>

B

</td>  
<td>

C

</td>  
<td>

D

</td> </tr>  
<tr>  
<td>

Persona1

</td>  
<td>

112

</td>  
<td>

2323

</td>  
<td>

888

</td>  
<td>

0

</td> </tr>  
<tr>  
<td>

Persona2

</td>  
<td>

12323

</td>  
<td>

333

</td>  
<td>

444

</td>  
<td>

11

</td> </tr> </table>



